### ISSUE TITLE
init docker-compose up

### ISSUE THREAD

**Issue by 0day1day** [ryhanson/lair-docker#11]
Hi when i follow your steps to run the container after several minutes i see this message:

> lair_api     | 2017/12/11 07:05:21 Could not connect to database. Error: no reachable servers
> lair_api     | 2017/12/11 07:05:33 Could not connect to database. Error: no reachable servers
> lair_api     | 2017/12/11 07:05:45 Could not connect to database. Error: no reachable servers
> lair_api     | 2017/12/11 07:05:57 Could not connect to database. Error: no reachable servers
> lair_api     | 2017/12/11 07:06:09 Could not connect to database. Error: no reachable servers
> lair_api     | 2017/12/11 07:06:21 Could not connect to database. Error: no reachable servers
> lair_api     | 2017/12/11 07:06:33 Could not connect to database. Error: no reachable servers
> lair_api     | 2017/12/11 07:06:45 Could not connect to database. Error: no reachable servers
> lair_api     | 2017/12/11 07:06:57 Could not connect to database. Error: no reachable servers
> lair_api     | 2017/12/11 07:07:09 Could not connect to database. Error: no reachable servers
> lair_api     | 2017/12/11 07:07:21 Could not connect to database. Error: no reachable servers
> lair_api     | 2017/12/11 07:07:33 Could not connect to database. Error: no reachable servers
> lair_api     | 2017/12/11 07:07:45 Could not connect to database. Error: no reachable servers
> lair_api     | 2017/12/11 07:07:57 Could not connect to database. Error: no reachable servers
> lair_api     | 2017/12/11 07:08:09 Could not connect to database. Error: no reachable servers
> lair_api     | 2017/12/11 07:08:21 Could not connect to database. Error: no reachable servers
> lair_api     | 2017/12/11 07:08:33 Could not connect to database. Error: no reachable servers
> lair_api     | 2017/12/11 07:08:45 Could not connect to database. Error: no reachable servers
> lair_api     | 2017/12/11 07:08:57 Could not connect to database. Error: no reachable servers
> lair_api     | 2017/12/11 07:09:09 Could not connect to database. Error: no reachable servers

Any idea about this issue?

**Comment by t1v0** [comment]
I managed to get mine working by changing the following line in the docker-compose.yml file:
From
entrypoint: ["/usr/bin/mongod", "--dbpath=/data/db", "--quiet", "--replSet", "rs0", "--logpath", "/var/log/mongodb.log", "--logappend"]
To:
command: mongod --bind_ip_all --replSet=rs0 --logpath=/dev/null

**Comment by cybert79** [comment]
apt-get install mongodb
and then change in docker-compose.yml 

lairdb:
                hostname: lairdb
                container_name: lair_db
                image: mongo
                restart: always
                volumes:
                        - $HOME/.lair/mongodb/data/db:/data/db
                          #entrypoint: ["/usr/bin/mongod", "--dbpath=/data/db", "--quiet", "--replSet", "rs0", "--logpath", "/var/log/mongodb.log", "--logappend"]
                entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet=rs0"]
