### ISSUE TITLE
meteor and npm error when docker-compose up is run

### ISSUE THREAD

**Issue by cybert79** [ryhanson/lair-docker#13]
lair_lair    | > meteor-dev-bundle@0.0.0 start /root/app/bundle/programs/server
lair_lair    | > node /root/app/bundle/main.js
lair_lair    |
lair_lair    | Note: you are using a pure-JavaScript implementation of bcrypt.
lair_lair    | While this implementation will work correctly, it is known to be
lair_lair    | approximately three times slower than the native implementation.
lair_lair    | In order to use the native implementation instead, run
lair_lair    |
lair_lair    |   meteor npm install --save bcrypt
lair_lair    |
lair_lair    | in the root directory of your application.
lair_lair    |
lair_lair    | /root/app/bundle/programs/server/node_modules/fibers/future.js:313
lair_lair    |                                          throw(ex);
lair_lair    |                                          ^
lair_lair    | MongoError: failed to connect to server [lairdb:27017] on first connect
lair_lair    |     at Pool.<anonymous> (/root/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:313:35)
lair_lair    |     at emitOne (events.js:116:13)
lair_lair    |     at Pool.emit (events.js:211:7)
lair_lair    |     at Connection.<anonymous> (/root/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:271:12)
lair_lair    |     at Object.onceWrapper (events.js:317:30)
lair_lair    |     at emitTwo (events.js:126:13)
lair_lair    |     at Connection.emit (events.js:214:7)
lair_lair    |     at Socket.<anonymous> (/root/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:165:49)
lair_lair    |     at Object.onceWrapper (events.js:315:30)
lair_lair    |     at emitOne (events.js:116:13)
lair_lair    | npm ERR! code ELIFECYCLE
lair_lair    | npm ERR! errno 1
lair_lair    | npm ERR! meteor-dev-bundle@0.0.0 start: `node /root/app/bundle/main.js`
lair_lair    | npm ERR! Exit status 1
lair_lair    | npm ERR!
lair_lair    | npm ERR! Failed at the meteor-dev-bundle@0.0.0 start script.
lair_lair    | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
lair_lair    |
lair_lair    | npm ERR! A complete log of this run can be found in:
lair_lair    | npm ERR!     /root/.npm/_logs/2018-05-03T13_41_32_053Z-debug.log
lair_api     | 2018/05/03 13:41:33 Could not connect to database. Error: no reachable servers

**Comment by leesoh** [comment]
I had a similar problem, but @cybert79's solution in #11 helped.
